server:
  port: 9000
spring:
  application:
    name: "loans"

  config:
    import: "optional:configserver:http://configserver:8072/"
  datasource:
    url: jdbc:mysql://localhost:3306/loans
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
    show-sql: true
  sql:
    init:
      mode: always

build:
  version: "1.0"

accounts:
  message: "welcome loans default"
  contactDetail:
    name: "John"
    email: "john@gmail.com"
  onCallSupport:
    - (080) 123456
    - (080) 987654
    -
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

