spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
    show-sql: true
  sql:
    init:
      mode: always


build:
  version: "1.0"

accounts:
  message: "welcome loans prod"
  contactDetail:
    name: "John"
    email: "john@gmail.com"
  onCallSupport:
    - (080) 123456
    - (080) 987654